// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { join } from "path";

// shared/data 디렉토리 경로 설정
const sharedDir = join(process.cwd(), 'shared');
const dataDir = join(sharedDir, 'data');
const dbPath = join(dataDir, 'gyegaboo.db');
const databaseUrl = `file:${dbPath}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || databaseUrl,
  },
});
